In [3]:
# Importujemy moduł torch, który jest podstawową biblioteką do obliczeń tensorowych w PyTorch.
import torch

# Importujemy klasę Tensor z modułu torch, która służy do tworzenia i manipulowania tensorami.
from torch import Tensor

In [4]:
print("Wersja torch", torch.__version__)

Wersja torch 2.0.1


In [5]:
# Ustawiamy ziarno generatora liczb losowych w bibliotece PyTorch na 42.
# To pozwala na kontrolowane generowanie tych samych "losowych" liczb przy każdym uruchomieniu programu.
# Jest to przydatne do uzyskiwania powtarzalnych wyników w przypadku używania funkcji losowych.
torch.manual_seed(42)

In [9]:
# Tworzymy nowy tensor o wymiarach (2, 3, 4).
# Tensor ten ma trzy wymiary: 2, 3 i 4.
x = Tensor(1, 2, 2, 3)
print(x)

tensor([[[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]]])


In [10]:
#Tworzymy tensor z listy podanych wartości
x = Tensor([[1, 2], [3, 4]])
print(x)

tensor([[1., 2.],
        [3., 4.]])


In [12]:
# Tworzymy nowy tensor o wymiarach (2, 3, 4) za pomocą funkcji torch.rand.
# Tensor ten jest wypełniony losowymi liczbami z zakresu [0, 1].
x = torch.rand(3, 3, 4)
print(x)

tensor([[[0.1053, 0.2695, 0.3588, 0.1994],
         [0.5472, 0.0062, 0.9516, 0.0753],
         [0.8860, 0.5832, 0.3376, 0.8090]],

        [[0.5779, 0.9040, 0.5547, 0.3423],
         [0.6343, 0.3644, 0.7104, 0.9464],
         [0.7890, 0.2814, 0.7886, 0.5895]],

        [[0.7539, 0.1952, 0.0050, 0.3068],
         [0.1165, 0.9103, 0.6440, 0.7071],
         [0.6581, 0.4913, 0.8913, 0.1447]]])


In [13]:
# Pobieramy wymiary tensora x za pomocą właściwości shape.
shape = x.shape
print("Wymiar tensora:", x.shape)

Wymiar tensora: torch.Size([3, 3, 4])


In [14]:
size = x.size()
print("Wymiar tensora:", size)

Wymiar tensora: torch.Size([3, 3, 4])


In [15]:
dim1, dim2, dim3 = x.size()
print("Wymiar:", dim1, dim2, dim3)

Wymiar: 3 3 4


In [17]:
#tensor dla 50 obrazów, 28x28 z rgb, losowe wartosci
y= torch.rand(50,28,28,3)
print(y)

tensor([[[[0.3024, 0.9916, 0.1605],
          [0.7980, 0.4953, 0.8236],
          [0.5991, 0.9676, 0.0814],
          ...,
          [0.0770, 0.4153, 0.3713],
          [0.9529, 0.3288, 0.0684],
          [0.7726, 0.6157, 0.9048]],

         [[0.9555, 0.2566, 0.1426],
          [0.1875, 0.5402, 0.3646],
          [0.6899, 0.2455, 0.5527],
          ...,
          [0.1325, 0.5316, 0.7053],
          [0.5064, 0.8162, 0.2366],
          [0.3614, 0.4904, 0.7046]],

         [[0.6745, 0.5337, 0.3589],
          [0.0113, 0.6367, 0.7194],
          [0.2898, 0.9836, 0.3154],
          ...,
          [0.1729, 0.1229, 0.1438],
          [0.3389, 0.0470, 0.5234],
          [0.7024, 0.1448, 0.7247]],

         ...,

         [[0.5079, 0.6635, 0.0154],
          [0.7044, 0.1955, 0.0054],
          [0.1205, 0.4629, 0.4021],
          ...,
          [0.4294, 0.2846, 0.9901],
          [0.2956, 0.7620, 0.1073],
          [0.4998, 0.2970, 0.5455]],

         [[0.7474, 0.3425, 0.4263],
          [0.5288

In [19]:
import numpy as np

#Tablica w Numpy
np_arr = np.array([[1, 2], [3, 4]])
#Konwersja Numpy na Torch
tensor = torch.from_numpy(np_arr)

print("Numpy array:", np_arr)
print("PyTorch tensor:", tensor)

Numpy array: [[1 2]
 [3 4]]
PyTorch tensor: tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [20]:
y.numpy()

array([[[[0.3023978 , 0.99159884, 0.16054189],
         [0.7980029 , 0.49528146, 0.82355684],
         [0.5990724 , 0.9676232 , 0.08143216],
         ...,
         [0.07704723, 0.41530967, 0.3713354 ],
         [0.9528789 , 0.32879514, 0.068367  ],
         [0.7726489 , 0.61573505, 0.90478784]],

        [[0.9554736 , 0.2565896 , 0.14257812],
         [0.18747246, 0.5402319 , 0.36455178],
         [0.6899302 , 0.24547571, 0.55266196],
         ...,
         [0.1324969 , 0.5316319 , 0.7053131 ],
         [0.5064079 , 0.8161843 , 0.23663682],
         [0.36144823, 0.49038368, 0.7046363 ]],

        [[0.6745269 , 0.533733  , 0.3588978 ],
         [0.01128823, 0.63665205, 0.7194438 ],
         [0.2897585 , 0.98364514, 0.31539714],
         ...,
         [0.17286068, 0.12293422, 0.14380962],
         [0.33893913, 0.04703087, 0.5234145 ],
         [0.7024262 , 0.14484829, 0.7247274 ]],

        ...,

        [[0.5079343 , 0.6634718 , 0.0153814 ],
         [0.70438015, 0.1954751 , 0.00536627]

In [18]:
tensor = torch.arange(4)
np_arr = tensor.numpy()

print("PyTorch tensor:", tensor)
print("Numpy array:", np_arr)

PyTorch tensor: tensor([0, 1, 2, 3])
Numpy array: [0 1 2 3]


In [27]:
#Obliczenia
x1 = np.array([[1,2,3],[3,2,1]])
x2 = torch.rand(2, 3).numpy()
y = x1 + x2

print("X1", x1)
print("X2", x2)
print("Y", y)

X1 [[1 2 3]
 [3 2 1]]
X2 [[0.14322561 0.98257416 0.37894726]
 [0.0541119  0.6106789  0.27239478]]
Y [[1.14322561 2.98257416 3.37894726]
 [3.0541119  2.61067891 1.27239478]]


In [13]:
# Funkcja ta generuje sekwencję liczb od 0 do 5 (6 elementów).
x = torch.arange(6)
print("X", x)

X tensor([0, 1, 2, 3, 4, 5])


In [32]:
# Zmieniamy kształt tensora x z (6,) na (2, 3) za pomocą metody .view().
x = x.view(2, 3)
print("X", x)

RuntimeError: shape '[2, 3]' is invalid for input of size 36

In [36]:
z = torch.rand(100,64,64)
straight = z.view(100, 64*64)
print(straight)

tensor([[0.0833, 0.3870, 0.0720,  ..., 0.3850, 0.6465, 0.7766],
        [0.4233, 0.7706, 0.9076,  ..., 0.3319, 0.4900, 0.8008],
        [0.9797, 0.3855, 0.9370,  ..., 0.3386, 0.8717, 0.4722],
        ...,
        [0.7549, 0.0315, 0.4628,  ..., 0.3965, 0.3310, 0.1681],
        [0.0957, 0.2479, 0.5466,  ..., 0.6492, 0.4928, 0.0917],
        [0.5576, 0.3040, 0.9965,  ..., 0.7400, 0.2110, 0.6122]])


In [15]:
x = torch.arange(12).view(3, 4)
print("X", x)

X tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [41]:
#Druga kolumna
print(x)
print(x[:, 1])

tensor([[[0.1053, 0.2695, 0.3588, 0.1994],
         [0.5472, 0.0062, 0.9516, 0.0753],
         [0.8860, 0.5832, 0.3376, 0.8090]],

        [[0.5779, 0.9040, 0.5547, 0.3423],
         [0.6343, 0.3644, 0.7104, 0.9464],
         [0.7890, 0.2814, 0.7886, 0.5895]],

        [[0.7539, 0.1952, 0.0050, 0.3068],
         [0.1165, 0.9103, 0.6440, 0.7071],
         [0.6581, 0.4913, 0.8913, 0.1447]]])
tensor([[0.5472, 0.0062, 0.9516, 0.0753],
        [0.6343, 0.3644, 0.7104, 0.9464],
        [0.1165, 0.9103, 0.6440, 0.7071]])


In [46]:
x[:0, -3:]

tensor([], size=(0, 3, 4))

In [48]:
#Pierwszy wiersz
print(x[0])

tensor([[0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753],
        [0.8860, 0.5832, 0.3376, 0.8090]])


In [ ]:
pics = torch.rand(200,28,28)
print(pics[99])

In [47]:
#Pierwsze dwa wiersze, ostatnia kolumna
print(x[:2, -1])

tensor([[0.8860, 0.5832, 0.3376, 0.8090],
        [0.7890, 0.2814, 0.7886, 0.5895]])
